"use client";

import { motion } from "framer-motion";
import {
    Brain,
    Layers,
    ShieldCheck,
    Activity,
    BarChart3,
    AlertTriangle,
} from "lucide-react";

export default function ModelInfo() {
    const strengths = [
        {
            icon: <Layers className="text-blue-600" />,
            title: "Random Forest Ensemble",
            desc: "An ensemble of decision trees trained on random feature subsets to reduce overfitting and improve generalization.",
        },
        {
            icon: <Activity className="text-green-600" />,
            title: "Captures Complex Patterns",
            desc: "Effectively models non-linear relationships between vitals such as blood pressure, BMI, and cholesterol.",
        },
        {
            icon: <ShieldCheck className="text-red-600" />,
            title: "Noise-Resistant",
            desc: "Robust against missing values, outliers, and noisy real-world medical data.",
        },
    ];

    return (
        <section className="relative py-20 px-6">
            {/* Background */}
            <div className="absolute inset-0 bg-gradient-to-br from-blue-50 via-white to-red-50 -z-10" />

            <div className="max-w-5xl mx-auto">
                {/* Header */}
                <motion.div
                    initial={{ opacity: 0, y: 30 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.6 }}
                    className="text-center mb-14"
                >
                    <span className="inline-block bg-blue-100 text-blue-600 px-4 py-1 rounded-full text-sm font-medium mb-4">
                        🤖 Machine Learning Model
                    </span>

                    <h2 className="text-4xl font-extrabold mb-4">
                        Cardiovascular <span className="text-blue-600">Risk Prediction Model</span>
                    </h2>

                    <p className="text-gray-600 max-w-3xl mx-auto text-lg">
                        This system uses a <b>Random Forest Classifier</b>, a widely adopted
                        machine learning model in healthcare analytics, designed to deliver
                        accurate, stable, and interpretable cardiovascular risk predictions.
                    </p>
                </motion.div>

                {/* Core Strengths */}
                <div className="grid md:grid-cols-3 gap-8 mb-16">
                    {strengths.map((item, i) => (
                        <motion.div
                            key={item.title}
                            initial={{ opacity: 0, y: 40 }}
                            whileInView={{ opacity: 1, y: 0 }}
                            viewport={{ once: true }}
                            transition={{ delay: i * 0.15 }}
                            className="bg-white rounded-2xl shadow-md hover:shadow-xl transition p-6"
                        >
                            <div className="flex items-center gap-3 mb-4">
                                <div className="p-3 bg-gray-100 rounded-xl">
                                    {item.icon}
                                </div>
                                <h3 className="font-semibold text-lg">
                                    {item.title}
                                </h3>
                            </div>

                            <p className="text-sm text-gray-600 leading-relaxed">
                                {item.desc}
                            </p>
                        </motion.div>
                    ))}
                </div>

                {/* How the Model Works */}
                <motion.div
                    initial={{ opacity: 0, scale: 0.96 }}
                    whileInView={{ opacity: 1, scale: 1 }}
                    viewport={{ once: true }}
                    transition={{ duration: 0.5 }}
                    className="bg-white rounded-2xl shadow-lg p-8 mb-12"
                >
                    <div className="flex items-center gap-3 mb-4">
                        <div className="p-3 bg-blue-100 rounded-xl">
                            <Brain className="text-blue-600" />
                        </div>
                        <h3 className="text-xl font-semibold">
                            How the Model Works
                        </h3>
                    </div>

                    <p className="text-gray-600 leading-relaxed">
                        Each decision tree in the Random Forest independently evaluates a
                        patient’s medical profile using different combinations of features.
                        The final prediction is generated by aggregating the outputs of all
                        trees (majority voting and probability averaging), resulting in a
                        more reliable and unbiased risk assessment.
                    </p>
                </motion.div>

                {/* Training & Evaluation */}
                <motion.div
                    initial={{ opacity: 0, y: 30 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    viewport={{ once: true }}
                    transition={{ duration: 0.5 }}
                    className="bg-white rounded-2xl shadow-lg p-8 mb-12"
                >
                    <div className="flex items-center gap-3 mb-4">
                        <div className="p-3 bg-green-100 rounded-xl">
                            <BarChart3 className="text-green-600" />
                        </div>
                        <h3 className="text-xl font-semibold">
                            Training & Evaluation Strategy
                        </h3>
                    </div>

                    <ul className="list-disc pl-6 text-gray-600 space-y-2">
                        <li>Data preprocessing included scaling, encoding, and outlier handling</li>
                        <li>Stratified train-test split to preserve class balance</li>
                        <li>Evaluation based on accuracy, recall, and probability calibration</li>
                        <li>Threshold tuning to reduce false negatives for high-risk patients</li>
                    </ul>
                </motion.div>

                {/* Safety & Limitations */}
                <motion.div
                    initial={{ opacity: 0, scale: 0.96 }}
                    whileInView={{ opacity: 1, scale: 1 }}
                    viewport={{ once: true }}
                    transition={{ duration: 0.5 }}
                    className="bg-white rounded-2xl shadow-lg p-8"
                >
                    <div className="flex items-center gap-3 mb-4">
                        <div className="p-3 bg-red-100 rounded-xl">
                            <AlertTriangle className="text-red-600" />
                        </div>
                        <h3 className="text-xl font-semibold">
                            Medical Safety & Limitations
                        </h3>
                    </div>

                    <p className="text-gray-600 leading-relaxed mb-4">
                        While the model provides strong predictive performance, it is not
                        intended to replace professional medical diagnosis. To enhance
                        safety, rule-based clinical thresholds are applied alongside model
                        predictions to flag potentially dangerous cases.
                    </p>

                    <p className="text-gray-600 leading-relaxed">
                        The system is designed as a <b>clinical decision support tool</b>,
                        assisting healthcare professionals and students in understanding
                        cardiovascular risk factors rather than making autonomous medical
                        decisions.
                    </p>
                </motion.div>
            </div>
        </section>
    );
}
