"use client";

import { motion } from "framer-motion";
import {
    AlertTriangle,
    ShieldCheck,
    HeartPulse,
    FileText,
} from "lucide-react";

export default function Disclaimer() {
    return (
        <section className="relative py-20 px-6">
            {/* Background */}
            <div className="absolute inset-0 bg-gradient-to-br from-red-50 via-white to-blue-50 -z-10" />

            <div className="max-w-5xl mx-auto">
                {/* Header */}
                <motion.div
                    initial={{ opacity: 0, y: 30 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.6 }}
                    className="text-center mb-14"
                >
                    <span className="inline-block bg-red-100 text-red-600 px-4 py-1 rounded-full text-sm font-medium mb-4">
                        ⚠️ Important Notice
                    </span>

                    <h2 className="text-4xl font-extrabold mb-4">
                        Medical <span className="text-red-600">Disclaimer</span>
                    </h2>

                    <p className="text-gray-600 max-w-3xl mx-auto text-lg">
                        Please read this disclaimer carefully before using the cardiovascular
                        risk assessment system.
                    </p>
                </motion.div>

                {/* Disclaimer Sections */}
                <div className="space-y-10">
                    {/* Educational Purpose */}
                    <motion.div
                        initial={{ opacity: 0, y: 30 }}
                        whileInView={{ opacity: 1, y: 0 }}
                        viewport={{ once: true }}
                        transition={{ duration: 0.5 }}
                        className="bg-white rounded-2xl shadow-lg p-8"
                    >
                        <div className="flex items-center gap-3 mb-4">
                            <div className="p-3 bg-blue-100 rounded-xl">
                                <FileText className="text-blue-600" />
                            </div>
                            <h3 className="text-xl font-semibold">
                                Educational & Research Use Only
                            </h3>
                        </div>

                        <p className="text-gray-600 leading-relaxed">
                            This application has been developed strictly for educational,
                            academic, and research purposes. It is intended to demonstrate the
                            application of machine learning techniques in healthcare analytics
                            and should not be used as a standalone medical tool.
                        </p>
                    </motion.div>

                    {/* No Medical Diagnosis */}
                    <motion.div
                        initial={{ opacity: 0, y: 30 }}
                        whileInView={{ opacity: 1, y: 0 }}
                        viewport={{ once: true }}
                        transition={{ duration: 0.5 }}
                        className="bg-white rounded-2xl shadow-lg p-8"
                    >
                        <div className="flex items-center gap-3 mb-4">
                            <div className="p-3 bg-red-100 rounded-xl">
                                <AlertTriangle className="text-red-600" />
                            </div>
                            <h3 className="text-xl font-semibold">
                                Not a Medical Diagnosis
                            </h3>
                        </div>

                        <p className="text-gray-600 leading-relaxed">
                            The predictions generated by this system are based on statistical
                            patterns learned from historical medical data using machine
                            learning models. These predictions should <b>not</b> be interpreted
                            as medical diagnoses, treatment recommendations, or clinical advice.
                        </p>
                    </motion.div>

                    {/* Human Oversight */}
                    <motion.div
                        initial={{ opacity: 0, y: 30 }}
                        whileInView={{ opacity: 1, y: 0 }}
                        viewport={{ once: true }}
                        transition={{ duration: 0.5 }}
                        className="bg-white rounded-2xl shadow-lg p-8"
                    >
                        <div className="flex items-center gap-3 mb-4">
                            <div className="p-3 bg-green-100 rounded-xl">
                                <ShieldCheck className="text-green-600" />
                            </div>
                            <h3 className="text-xl font-semibold">
                                Human Oversight Required
                            </h3>
                        </div>

                        <p className="text-gray-600 leading-relaxed">
                            The system is designed as a <b>decision support tool</b> to assist
                            learning and awareness. All health-related decisions must be made
                            by qualified healthcare professionals who can consider complete
                            clinical context, medical history, and physical examination.
                        </p>
                    </motion.div>

                    {/* Professional Advice */}
                    <motion.div
                        initial={{ opacity: 0, scale: 0.96 }}
                        whileInView={{ opacity: 1, scale: 1 }}
                        viewport={{ once: true }}
                        transition={{ duration: 0.5 }}
                        className="bg-white rounded-2xl shadow-lg p-8"
                    >
                        <div className="flex items-center gap-3 mb-4">
                            <div className="p-3 bg-orange-100 rounded-xl">
                                <HeartPulse className="text-orange-600" />
                            </div>
                            <h3 className="text-xl font-semibold">
                                Consult a Healthcare Professional
                            </h3>
                        </div>

                        <p className="text-gray-600 leading-relaxed font-medium">
                            Always consult a qualified doctor or licensed healthcare provider
                            for medical concerns, diagnosis, or treatment decisions. Do not
                            delay or disregard professional medical advice based on information
                            generated by this application.
                        </p>
                    </motion.div>
                </div>
            </div>
        </section>
    );
}
